Where can foreigners donate to support Ukraine?

* National

https://ukrainewar.carrd.co/

* Regional

** Kyiv

*** Kyiv Humanitarian Platform

https://potreby.kyivcity.gov.ua/

Organized and endorsed by the Mayor of Kyiv to supply food, medicine
to citizen in need. This org may reach people faster and cover more
needs than international orgs that have limited access and lower risk
tolerance.

I am personally supporting this org financially as Kyiv is my home
town and I have relatives still there.

* Refugees

As of Mar 3, more than a million people crossed the borderes to flee
war in Ukraine ([[https://twitter.com/FilippoGrandi/status/1499156937644118022][link]]).

Refugees need help inside Ukraine as they travel and then need help
settling in once they cross the border. Ukraininan orgs have the edge
in operating inside Ukraine and navigating risks of open conflict,
while international orgs have the advantage in having experience how
to organized relief efforts in countries receiving refugees, and they
do some operations inside Ukraine also.

** Amnesty

Amnesty is definitely doing great work:

https://donate.amnestyusa.org/page/100216/donate/1

** Ukrainian Education Center

This is a small religious org I was supporting in Kyiv throughout the
years before the war. Their senior staff is now in Slovakia and
they're reorganizing to support refugees and are asking for help for
their efforts as well as the efforts of their Polish partners helping
refugees.

https://www.uecandme.org/

** Misc

I need to do research to find out what more to recommend.

See this [[https://www.today.com/news/news/5-verified-charities-working-help-ukrainians-invasion-rcna17590][starter list]].
