Where can foreigners donate to support Ukraine?

* National

https://ukrainewar.carrd.co/

* Regional

** Kyiv

*** Kyiv Humanitarian Platform

https://potreby.kyivcity.gov.ua/

Organized and endorsed by the Mayor of Kyiv to supply food, medicine
to citizen in need. This org may reach people faster and cover more
needs than international orgs that have limited access and lower risk
tolerance.

I am personally supporting this org financially as Kyiv is my home
town and I have relatives still there.



** Mykolaiv

Ochakiv is a small town in the Mykolaiv region in the South.
Previously I have contributed to a collecton for an electrical
generator, but there are still some open needs in the community as of
Apr 26, so leaving it open here.

USD Transfers

| Recipient   | OCHAKIVSKYY MISKYY BLAHODIYNYY FOND OCHAKIV DLIA LIUDEY                         |
| Address     | 57508, Mykolayivska obl., misto Ochakiv, VULYTSIA KHETAHUROVA KOSTY, budynok 44 |
| Phone       | +380515430854                                                                   |
| USREOU code | 37237595                                                                        |
| IBAN        | IBAN UA58 305299 00000 26001041715237                                           |
| Bank        | PrivatBank                                                                      |
| SWIFT       | PBANUA2x                                                                        |
| Notes       | Donation                                                |

Correspondent Banks

| Bank                                       |      Account | SWIFT      |
|--------------------------------------------+--------------+------------|
| JP Morgan Chase Bank, New York, USA        | 001-1-000080 | CHASUS33   |
| The Bank of New York Mellon, New York, USA | 890-0085-754 | IRVT US 3N |

Переводи у гривні

| Фонд        | Очаківський міський благодійний фонд "Очаків для Людей"  |
| Адреса      | 57508, Миколаївська обл., м. Очаків, вул. Хетагурова, 44 |
| Тел         | +380515430854                                            |
| ЄДРПОУ      | 37237595                                                 |
| IBAN        | IBAN UA68 320478 00000 26001924892759                    |
| Банк        | АБ Укргазбанк                                            |
| Призначення | Внесок на благодійність                                  |


* Refugees

As of Mar 3, more than a million people crossed the borderes to flee
war in Ukraine ([[https://twitter.com/FilippoGrandi/status/1499156937644118022][link]]).

Refugees need help inside Ukraine as they travel and then need help
settling in once they cross the border. Ukraininan orgs have the edge
in operating inside Ukraine and navigating risks of open conflict,
while international orgs have the advantage in having experience how
to organized relief efforts in countries receiving refugees, and they
do some operations inside Ukraine also.

** Amnesty

Amnesty is definitely doing great work:

https://donate.amnestyusa.org/page/100216/donate/1

** Ukrainian Education Center

This is a small religious org I was supporting in Kyiv throughout the
years before the war. Their senior staff is now in Slovakia and
they're reorganizing to support refugees and are asking for help for
their efforts as well as the efforts of their Polish partners helping
refugees.

https://www.uecandme.org/

** Misc

I need to do research to find out what more to recommend.

See this [[https://www.today.com/news/news/5-verified-charities-working-help-ukrainians-invasion-rcna17590][starter list]].
